version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smfg-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "9090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: oz@oz.com
      PGADMIN_DEFAULT_PASSWORD: oz
    restart: unless-stopped

  rabbitmq:
    image: docker.seanksmith.me/custom-rabbit:v0.0.1
    restart: unless-stopped
    ports:
      - "9091:15672"
      - "5672:5672"

volumes:
  postgres-data: